bbr:
  name: body-based-router
  replicas: 1
  image:
    name: bbr
    hub: registry.k8s.io/gateway-api-inference-extension
    tag: v1.2.0-rc.1
    pullPolicy: Always
  port: 9004
  healthCheckPort: 9005

provider:
  name: none

inferenceGateway:
  name: inference-gateway
